### ISSUE TITLE
Failure to initLlama on Xiaomi phones.

### ISSUE THREAD

**Issue by Vali-98** [mybigday/llama.rn#42]
Hello again, I've received reports from users of [ChatterUI](https://github.com/Vali-98/ChatterUI) that model loading fails on Xiaomi branded phones:

Confirmed not working:
- Xiaomi Poco F5 - Android 14
- Redmi 10C - Android 13

I've also queried about other phones, and got a few responses for working devices.

Confirmed working:
- Samsung A71 - Android 13
- Samsung M52 - Android 13

Version used:
- llama.rn 0.3.0-rc.14

Logcat response on the tested Poco F5:

```
RNLLAMA_ANDROID_JNI: [RNLlama] is_model_loaded false
```

There aren't enough users to confirm this is a trend across all Xiaomi phones, but it is peculiar.

**Comment by jhen0409** [comment]
I don't have a Xiaomi phone now. One possibility that comes to my mind is related to -march:

https://github.com/mybigday/llama.rn/blob/b1fb538f7f0b6178b46682a26ae29e1ba1bb7952/android/src/main/CMakeLists.txt#L38

Can you try `armv8.2-a+fp16+dotprod` or other options?

**Comment by Vali-98** [comment]
> Can you try `armv8.2-a+fp16+dotprod` or other options?

Tested this, not working.

I also tested version rc.9 to rc.13, all also non-functional. I assume this is an issue on the OS side for whatever reason.

**Comment by Vali-98** [comment]
This issue seems to be resolved after updating to Expo SDK 50.
