### ISSUE TITLE
Update llamacpp module to latest

### ISSUE THREAD

**Issue by Vali-98** [mybigday/llama.rn#44]
I am having troubling updating the llamacpp submodule mysel. Could the project be updated as llamacpp has added support for a few new base models that currently do not work in llama.rn?

**Comment by Ar57m** [comment]
@jhen0409 it would be very useful if could update llama to the lastest version, there are a lot of new models supported like qwen1.5, stablelm2, gemma(from Google) etc.

**Comment by jhen0409** [comment]
Updated by #45. Sorry for the delay.

**Comment by Ar57m** [comment]
> Updated by #45. Sorry for the delay.

thank you 🤗

**Comment by Ar57m** [comment]
> Updated by #45. Sorry for the delay.

when you have some time to update it again, mamba support is merged on llama.cpp 🎉
