### ISSUE TITLE
Implementing optimizations from layla

### ISSUE THREAD

**Issue by Vali-98** [mybigday/llama.rn#50]
Layla is a project that also integrates llamacpp for mobile use:
https://github.com/l3utterfly/llama.cpp/tree/layla-build

After some quick testing, it does seem like Layla's fork for llamacpp runs models far faster on android than llama.rn, almost twice as fast in some cases with 7b models.

It would be wonderful in these improvements were added to llama.rn as well.

**Comment by jhen0409** [comment]
Interesting, I just did a quick look, is it enabled CLBlast?

https://github.com/ggerganov/llama.cpp/compare/master...l3utterfly:llama.cpp:layla-build

/cc @l3utterfly

**Comment by l3utterfly** [comment]
Yes, the Layla build as CLBlast enabled
________________________________
