### ISSUE TITLE
Sync llamacpp again 

### ISSUE THREAD

**Issue by GameOverFlowChart** [mybigday/llama.rn#63]
Llamacpp added support for gema 2 which is a very promising model family.

**Comment by GameOverFlowChart** [comment]
Hmm it seems like the support still isn't 100% there, maybe it's better to wait a while before the sync.
https://github.com/ggerganov/llama.cpp/pull/8197

**Comment by a-ghorbani** [comment]
if it is helpul see: https://github.com/mybigday/llama.rn/pull/67
