### ISSUE TITLE
RWKV support (sync llama.cpp)

### ISSUE THREAD

**Issue by tomasmcm** [mybigday/llama.rn#77]
Llama.cpp added support for RWKV models in https://github.com/ggerganov/llama.cpp/releases/tag/b3651
Can you sync the version llama.rn uses so that we can try those models? They are very lightweight and need a lot less RAM than transformers models, so it's a great fit for mobile devices.

**Comment by a-ghorbani** [comment]
Any chance this might get synced with the latest llama.cpp? I was going to give it a shot, but noticed a number of refactoring and changes in llama.cpp and didn’t want to risk messing up the codebase.

**Comment by a-ghorbani** [comment]
Kudos to @Vali-98 A synced version is available here: https://github.com/Vali-98/cui-llama.rn

**Comment by Vali-98** [comment]
Hey there, just a reminder that cui-llama.rn currently lacks a lot of Swift / IOS integration for the new features added. I cannot guarantee that it'll work.
