### ISSUE TITLE
Expose Template Parameter for getFormattedChat

### ISSUE THREAD

**Issue by a-ghorbani** [mybigday/llama.rn#84]
By exposing this parameter, we can enable users to customize and pass their templates, not just the ones that come with gguf.

**Comment by jhen0409** [comment]
This is easy to expose and it will be added soon, but I'll recommend user to use [jinja parser](https://www.npmjs.com/package/@huggingface/jinja) for make prompt from template, currently the chat template in llama.cpp is a bit limited:

https://github.com/ggerganov/llama.cpp/blob/f245cc28d4eb900efad0bc740145f58d713c6e4f/src/llama.cpp#L21637-L21639
