### ISSUE TITLE
Can't compile: 'ReactCommon/RCTTurboModule.h' file not found

### ISSUE THREAD

**Issue by XEmAX32** [mybigday/llama.rn#97]
Can't compile project, getting the following error from Xcode 

```
'ReactCommon/RCTTurboModule.h' file not found
```
file is RNLlamaSpec.h

versions:
```
    "llama.rn": "^0.4.3",
    "react": "18.3.1",
    "react-native": "0.76.3",
    "react-native-document-picker": "^9.3.1",
    "react-native-fs": "^2.20.0"
```

**Comment by XEmAX32** [comment]
for anyone else having the same problem I solved it by changing

```
#import <ReactCommon/RCTTurboModule.h>
```
to
```
#import "RCTTurboModule.h"
```

in file RNLlamaSpec.h

no idea if this is a long-term solution neither if it's just my problem

**Comment by alexyaroshuk** [comment]
Had the same error. Added this to the YAML when building for ios, I believe, was the solution

xcodebuild \
...
RCT_NEW_ARCH_ENABLED=0 \
...

**Comment by dsx1986** [comment]
> for anyone else having the same problem I solved it by changing
> 
> ```
> #import <ReactCommon/RCTTurboModule.h>
> ```
> 
> to
> 
> ```
> #import "RCTTurboModule.h"
> ```
> 
> in file RNLlamaSpec.h
> 
> no idea if this is a long-term solution neither if it's just my problem

same here. but this is under generated/ios
